//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bcciApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series1
    {
        public int MatchID { get; set; }
        public string MatchName { get; set; }
        public string Team1 { get; set; }
        public string Team2 { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public string Venue { get; set; }
        public Nullable<int> SeriesID { get; set; }
        public string SeriesName { get; set; }
        public Nullable<System.DateTime> SeriesStartDate { get; set; }
        public Nullable<System.DateTime> SeriesEndDate { get; set; }
    }
}
